name: Submit a Repo Creation request
description: Use an Action to create the repository
title: "Repo:Create"
labels: ["create-repo"]

body:
  - type: input
    id: repo-name
    attributes:
      label: Name of the Repo
      description: What is the name of the new repo?
      placeholder: 
    validations:
      required: true
